/*
 * This source file was generated by the Gradle 'init' task
 */
package com.tazzledazzle

import com.xenomachina.argparser.ArgParser
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class MapleTest {
    @Test fun mapleHasAGreeting() {
        val classUnderTest = Maple()
        assertNotNull(classUnderTest.greeting, "maple should have a greeting")
    }

    @Test fun mapleAcceptsCommandLineArgs() {
        val args = arrayOf("-b","test-bom.json","-v", "arg2")
        MapleArgs(ArgParser(args)).run {
            assertEquals("test-bom.json", bom, "Expected bom to be 'test-bom.json'")
            assertEquals("arg2", version, "Expected version flag to be set")
            assertEquals(false, liveRun, "Expected liveRun to be false by default")
        }

    }
}
