/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull

class MapleTest {
    @Test fun mapleHasAGreeting() {
        val classUnderTest = Maple()
        assertNotNull(classUnderTest.greeting, "maple should have a greeting")
    }
}
