name: CI

on:
  push:
     branches: [ main ]
  pull_request:
     branches: [ main ]


jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-java@v4
            with:
              distribution: temurin
              java-version: 21
          - name: Cache Gradle
            uses: actions/cache@v4
            with:
               path: |
                ~/.gradle/caches
                ~/.gradle/wraper
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                restore-keys: |
                  ${{ runner.os }}-gradle-
          - name: Build
            run: ./gradlew build --no-daemon
