name: Nightly Remote E2E

on:
  schedule:
    - cron: "0 09 * * *"   # 09:00 UTC ~ 02:00 PST
  workflow_dispatch:

permissions:
  contents: write

env:
  ORG: ${{ github.repository_owner }}
  PREFIX: maple-fixture-
  VERSION: 1.0.0
  COUNT: 3

jobs:
  remote-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup GH auth
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_FOR_FIXTURES }}  # create a PAT with repo delete/create scopes
        run: gh auth status || gh auth login --with-token <<< "$GH_TOKEN"

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Generate GH fixtures
        run: ./gradlew run --args="fixtures init --remote github --org $ORG --count $COUNT --prefix $PREFIX --root /tmp/remote-fixtures --version $VERSION"

      - name: Run Maple plan
        run: ./gradlew run --args="plan --bom /tmp/remote-fixtures/fixtures-bom.json --version $VERSION"

      - name: Run Maple full
        run: ./gradlew run --args="run --bom /tmp/remote-fixtures/fixtures-bom.json --version $VERSION"

      - name: Upload run summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-run-summary
          path: .maple/state/*.json

      - name: Destroy GH fixtures
        if: always()
        run: ./gradlew run --args="fixtures destroy --remote github --org $ORG --prefix $PREFIX --root /tmp/remote-fixtures"
